# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/camera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/camera


PRODUCT_PACKAGES += \
    libcamera_algoup_jni.xiaomi \
    libcamera_mianode_jni.xiaomi \
    libmicampostproc_client \
    vendor.xiaomi.hardware.campostproc@1.0_system \
    MiuiCamera

PRODUCT_PACKAGES += \
    libcamera_algoup_jni.xiaomi_libcamera_algoup_jni.xiaomi_symlink64 \
    libcamera_mianode_jni.xiaomi_libcamera_mianode_jni.xiaomi_symlink64
